// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnlvhmmjxmizlfqbjefl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubHZobW1qeG1pemxmcWJqZWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjYxNDAsImV4cCI6MjA2MjQ0MjE0MH0.5mYiVnlsqKT_sO-fzRAVHdA50pzuI0250ZbGq7QYt9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);